apiVersion: v1
kind: Namespace
metadata:
  name: dynamic-mig-jobs
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: mig-test-service-account
  namespace: dynamic-mig-jobs
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: mig-test-anyuid-scc-binding
subjects:
- kind: ServiceAccount
  name: mig-test-service-account
  namespace: dynamic-mig-jobs
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: system:openshift:scc:anyuid
---
apiVersion: resource.k8s.io/v1beta1
kind: ResourceClaimTemplate
metadata:
  name: mig-1g-10gb
  namespace: dynamic-mig-jobs
spec:
  spec:
    devices:
      requests:
      - name: mig
        deviceClassName: mig.nvidia.com
        selectors:
        - cel:
            expression: 'device.attributes["gpu.nvidia.com/mig-profile"].string == "1g.10gb"'
---
apiVersion: v1
kind: Pod
metadata:
  name: mig-test-pod
  namespace: dynamic-mig-jobs
spec:
  restartPolicy: Never
  serviceAccountName: mig-test-service-account
  containers:
  - name: mig-test
    image: nvcr.io/nvidia/cuda:12.4.0-base-ubi9
    command: ["nvidia-smi"]
    securityContext:
      runAsUser: 1000
    resources:
      claims:
      - name: migdev
  resourceClaims:
  - name: migdev
    resourceClaimTemplateName: mig-1g-10gb
