FROM nvcr.io/nvidia/cuda:12.4.1-devel-ubi9

WORKDIR /

RUN dnf -y update && \
    dnf -y install boost-devel cmake make git openssh-server openssh-clients && \
    dnf clean all && \
    rm -rf /var/cache/yum
RUN git clone --single-branch --branch=main --depth=1 https://github.com/NVIDIA/nvbandwidth.git
RUN cd nvbandwidth && cmake . && make && chmod +x nvbandwidth && cp nvbandwidth /usr/bin/nvbandwidth

ENTRYPOINT [ "nvbandwidth" ]